sonar.projectKey=drevia_bobapp-backend
sonar.projectName=BobApp Backend
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src/main
sonar.exclusions=src/main/resources/**
sonar.coverage.exclusions=src/main/resources/**
sonar.java.coverage.reportPaths=target/site/jacoco/jacoco.xml
sonar.java.binaries=target/classes
sonar.branch.name=main

